### ISSUE TITLE
How do I read the files now? I think their encoded?

### ISSUE THREAD

**Issue by TheDynomike** [aianlinb/VisualGGPK2#52]
I utilize the LibBundle and LibGGPK dll's to parse through the ggpk files.

I then download a target file (finding it by supplying the hash).

But when I download the file in my custom app, the file is encoded? How do I decode it?

Here's how I download the FileRecord
![Untitled](https://github.com/aianlinb/VisualGGPK2/assets/10679481/a6188da3-c5d1-4b98-b552-6d31253d349c)

Here's what the file looks like when I download it
![Untitled](https://github.com/aianlinb/VisualGGPK2/assets/10679481/fb51f049-e7c7-41bb-8b05-38ead58e175e)

**Comment by TheDynomike** [comment]
Update nvm, my LibBundle was behind. I'll try the new dll

**Comment by aianlinb** [comment]
@TheDynomike See README.md, using this repository for development is not recommended
![image](https://github.com/aianlinb/VisualGGPK2/assets/29705994/d7d6fd6b-36d9-4ebe-b1ac-7d6fe0badaa0)
